### ISSUE TITLE
TST: `test_kda.py` recommendations

### ISSUE THREAD

**Issue by nawtrey** [Becksteinlab/kda#3]
This issue was originally opened in GitLab and used to track testing ideas. I've consolidated them into a single list below, but future testing ideas will have their own issues. 

### Testing ideas:
- [x] Add tests that sum probabilities and check if almost equal to 1
- [x] Check if all generated flux diagrams contain only 1 cycle -- redundant 
- [x] For existing tests, add matrix method verification via `kda.solve_matrix()`
- [x] Add tests that count numbers of partial and directional partial diagrams 
- [x] Add test for `kda.calculate_pi_difference()` to verify the fix for issue #15 
- [x] Add regression test that counts the number of flux diagrams generated for multiple models. This is already halfway implemented, but needs to be expanded to include more known cases
- [ ] Add additional unit tests for `calculations.calc_thermo_force()` (similar to `test_thermo_force_4WL`) where each test verifies the output of multiple models (4-state, 5-state). 
- [ ] Add unit tests for `calculations.calculate_pi_difference()` where each test verifies the output of multiple models (4-state, 4-state with leakage, 5-state)
~Add assertion to `test_flux_diagram_counts` verifying each flux diagram contains only 1 unique cycle~
- [ ] Add assertion to `test_diagram_counts` verifying the list of edges for each partial and directional diagram contains all nodes in the input diagram

**Comment by nawtrey** [comment]
For existing tests, add matrix method verification via kda.solve_matrix().

**Comment by nawtrey** [comment]
Write a test for kda.generate_flux_diagrams():
 - Check if all generated flux diagrams contain only 1 cycle
 - Check that each diagram contains the correct number of unique edges
 - Check that list of edges contains all node in the input diagram

**Comment by nawtrey** [comment]
Add test that counts numbers of partial, directional partial, and flux diagrams for each model since these are known.

**Comment by nawtrey** [comment]
Add test for kda.calculate_pi_difference() to verify the fix for issue #15.

**Comment by nawtrey** [comment]
To consolidate the tests recommended in this issue:
- [ ] Add tests that sum probabilities and check if almost equal to 1
- [ ] Add tests that verify flux diagrams
- [ ] For existing tests, add matrix method verification via `kda.solve_matrix()`
- [ ] Check if all generated flux diagrams contain only 1 cycle
- [ ] Check that each flux diagram contains the correct number of unique edges
- [ ] Check that list of edges contains all nodes in the input diagram
- [ ] Add test that counts numbers of partial, directional partial, and flux diagrams for each model since these are known.
- [ ] Add test for `kda.calculate_pi_difference()` to verify the fix for issue #15 
- [ ] Add more tests for functions in #15 where each test verifies the output of multiple models

**Comment by nawtrey** [comment]
It might be worthwhile to make some `pytest` fixtures for specific models (3 state, 4 state, 4 state with leakage, etc.) that can be used across the entire testing module. That would make some of the tests easier since I wouldn't have to input a matrix, generate the edges, etc.

**Comment by nawtrey** [comment]
With #59 merged I checked off the corresponding task.

**Comment by nawtrey** [comment]
Remaining tasks were addressed in https://github.com/Becksteinlab/kda/commit/a1e6658f5b351e4e513b30b97590af41010e2699. Closing.
