### ISSUE TITLE
Cleanup `plotting.py`

### ISSUE THREAD

**Issue by nawtrey** [Becksteinlab/kda#34]
As discussed in https://github.com/Becksteinlab/kda/pull/33#issuecomment-869215992, the `plotting.py` module needs to be reorganized and cleaned up more. 

## TODO:

- [x]  Move the plotting code into functions targeted at specific plotting cases (single plot, multiple plots, panel, etc.)
- [x]  Update the defaults to use panel plots since these are generally the easiest to read 
- [x]  Move remaining repeated code (like the `cbt=True` code) into functions 
- [ ]  Improve documentation overall, and add examples
- [ ]  Add tests to `test_plotting.py` that more rigorously test the smaller functions

**Comment by nawtrey** [comment]
With gh-45 merged, I've checked off some of the above tasks.

**Comment by nawtrey** [comment]
With issues #46, #49 and #50 opened, the remaining tasks here are being addressed separately. Closing.
